### ISSUE TITLE
「戻る」ボタンを押して遷移した先で、Observable の subscribe が効かない

### ISSUE THREAD

**Issue by 0918nobita** [0918nobita/Tsundoku#17]
現在、起動後のログイン処理は以下の段階を踏んで行われます。

1. Firebase SDK の設定 (``app/services/firebase.service.ts``)
2. Firebase Authentication を用いたログイン処理と UID の取得 (``app/services/account.service.ts``)
3. Cloud Functions にデプロイした関数 ``getUserByUID`` に UID を渡して呼び出し、ユーザー情報 (``shared/entity.ts`` で定義した ``User`` 型の値)を取得する

``AccountService`` 側でログイン処理が完了すると、``login$`` フィールド (Observable) で ``User`` 型の値を流すため、``AppComponent``, ``BookshelfComponent`` ではこの Service を DI して、 ``ngOnInit`` メソッドの処理中に ``login$`` を subscribe することによって、ログイン後の動作を記述しています。

具体的には、``AppComponent`` ではログイン後に積読本棚画面 (``/bookshelf``, ``BookshelfComponent``) へ遷移させます。

ログインに失敗した場合は、``AccountService`` 側で ``Router`` を用いてログインページへ強制的に遷移させるようになっています。

しかし、実際にログインして積読本棚画面を表示してみると、``/bookshelf`` に直リンクした場合には正常に ``ngOnInit`` 中に subscribe が行われて本のサムネイル一覧が表示されるのに対し、サムネイルをクリックして遷移した先の ``/bookDetails/xxx`` で「戻る」ボタンを押して積読本棚画面に戻ると、``ngOnInit`` 自体は呼び出されるものの、 **subscribe は効かず、結果としてサムネイル一覧が表示されません。**

※「戻る」ボタンは、BackComponent (``app/back/back.component.ts``) で実装されています。  
``Location`` を DI して、back メソッドを呼び出すことで遷移元のページに戻るようになっています。

**Comment by 0918nobita** [comment]
``/bookshelf`` に直リンクした場合、このような画面が表示されます(これが想定していた正しい動作です)

![画像](https://res.cloudinary.com/tsundoku/image/upload/v1538454240/screen.png)

**Comment by musou1500** [comment]
@0918nobita ちなみに，ログイン時に，自動的に `/bookshelf` に遷移した場合でも，サムネイルは正常に表示されますか？

**Comment by 0918nobita** [comment]
先程の画面で、「Linuxのしくみ」のサムネイルをクリックすると ``/bookDetails/477419607X`` に遷移し、このような画面になります

![画像](https://res.cloudinary.com/tsundoku/image/upload/v1538454242/screen2.png)

**Comment by 0918nobita** [comment]
@musou1500 その場合にどうなるかは、まだテストできてません

**Comment by 0918nobita** [comment]
@musou1500 さっきテストしてみましたが表示されませんでした

**Comment by 0918nobita** [comment]
正常に表示できていない積読本棚画面では、このように「Now Loading...」がずっと表示されたままの状態になります

![画像](https://res.cloudinary.com/tsundoku/image/upload/v1538454243/screen3.png)

**Comment by musou1500** [comment]
@0918nobita 
なるほどですね．
僕の方で動作確認できていないのですが， "戻る"ボタンを押して `bookshelf` 画面に遷移した場合，`login$` に値はそもそも流されていない，という認識です．

例えば，以下のようなコードを考えてみてください．
```javascript
const user$ = new Subject<User>();
setTimeout(() => user.next({ name: 'hogefuga' }), 500);
setTimeout(() => {
  user$.subscribe(user => console.log(user));
}, 1000)
```

* 0.5秒後に `user$` に値を流す
* 1秒後に subscribe

この場合，結果としては何も出力されません．
HotなObservableは，ColdなObservableとは違い，値を流した後で subscribeした場合，値を受け取ることは出来ない，という感じです．

もしも，「最後に流した値を保持しておきたい」ということであれば， `BehaviorSubject` や `ReplaySubject` を使うと良いです．
`BehaviorSubject` は，最後に流した値を保持していて， subscribeされたタイミングでその値を流してくれます．

**Comment by 0918nobita** [comment]
@musou1500 なるほど…``BehaviorSubject``を使って上手くいくか試してみます
ありがとうございます！

**Comment by musou1500** [comment]
@0918nobita あと，これは余談なのですが，特定の条件下でページへのアクセスを弾きたい，みたいなユースケースでは，`@angular/router` のguardを使うと便利です．
https://angular.io/guide/router#guards

**Comment by 0918nobita** [comment]
@musou1500 ``BehaviorSubject`` を使うと解決しました！ https://github.com/TsundokuApp/Tsundoku/commit/922b047ada3d978272d3d6463aa74c98193a05b1

**Comment by musou1500** [comment]
@0918nobita よかったです！！firebase-sdkについては，[angularfire](https://github.com/angular/angularfire2)を使うと，firebase関連のクラスをDIできるようになるので，ぜひ試してみてください．

**Comment by 0918nobita** [comment]
@musou1500 了解です！Route Guardsについても調べてみます
本当にいろいろと教えていただきありがとうございました！
